//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchandiser
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetUserRole
    {
        [Key]
        public string UserId { get; set; }
        [Key]
        public string RoleId { get; set; }
        [Key]
        public System.Guid CompanyId { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual Company Company { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
