//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchandiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ModifiedByUserId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedByUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
