//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchandiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchandise
    {
        public string Id { get; set; }
        public string AspNetUsersId { get; set; }
        public int Quantity { get; set; }
        public string Name { get; set; }
        public string UPCCode { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
