//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchandiser
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectSurvey
    {
        public System.Guid Id { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid LocationId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> SurveyCreated { get; set; }
    }
}
