
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Merchandiser
{

using System;
    using System.Collections.Generic;
    
public partial class SelectLocation
{

    public int Id { get; set; }

    public int CustomerId { get; set; }

    public Nullable<int> CompanyId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public Nullable<System.DateTime> SurveyCreated { get; set; }

}

}
